### ISSUE TITLE
VSize too big using 15khz

### ISSUE THREAD

**Issue by PapiFed** [MiSTer-devel/Arcade-IremM72_MiSTer#1]
It could be something wrongly setup on my end (I strongly doubt that is the case) but I noted that Dragon Breed, R-Type and Gallop all have a vertical size of the picture extremely stretched.
Even if I reduce quite a bite the vertical size on my CRTs the HUD at the bottom of the screen is barely visible.
I am using "Normal" video timing.

**Comment by wickerwaka** [comment]
The latest release adds support for some CRT adjustments which might help a little. However, the core is 256 lines tall, so some displays are just going to have issues displaying it.

**Comment by sorgelig** [comment]
Need to mention that Arcade CRT is not the same as consumer TV, so some/many arcades simply cannot be fully compatible with consumer TV.

**Comment by PapiFed** [comment]
Thanks for the additional options, they are greatly appreciated by all CRT users. These options do not improve the situation.
Maybe a custom_video mode could be the solution here.

**Comment by PapiFed** [comment]
Just tested with the 20220910 release on a different CRT and things look fine. Seems to be my either my 2950QM or something in my setup for that CRT being the culprit. Closing this issue.
