### ISSUE TITLE
Rom error on Air Duel (world)

### ISSUE THREAD

**Issue by Schermobianco** [MiSTer-devel/Arcade-IremM72_MiSTer#10]
Hi Martin, I have an error during startup of Air Duel - world (Japan work fine)

Already tried to redownload rom with update_all

![IMG_20221009_230203.jpg](https://user-images.githubusercontent.com/89546473/194779585-a9251f4f-f97d-4816-9cd9-4a2ca3ca759e.jpg)

**Comment by sorgelig** [comment]
Different mame versions have different rom sets. So it may lead to this result.

**Comment by Schermobianco** [comment]
Hi Sorg, yes i checked the mame chengelog and from the 0.246 the rom is OK

![image](https://user-images.githubusercontent.com/89546473/194864761-1ca2e946-ce78-4a6f-a535-152217de0718.png)

i suggest to change the mra mame version _(Air Duel (World, M72 hardware).mra)_ 
from 
`<mameversion>0245</mameversion>`
to
`<mameversion>0248</mameversion>`

**Comment by wickerwaka** [comment]
I have updated both Air Duel mras to point to version 248 and I have also fixed the mcu rom so it points to the correct World version. MAME 248 or newer is not yet support me update_all's arcade rom database, so you will need to acquire the roms manually for it to work.
