### ISSUE TITLE
Add SNAC UserIO support request

### ISSUE THREAD

**Issue by Zagg3r** [MiSTer-devel/Arcade-IremM72_MiSTer#15]
Could you add UserIO/SNAC support for DB15 Joystick, please?

**Comment by wickerwaka** [comment]
I don't have a SNAC setup or any DB15 hardware, so I would not be able to test this. If someone who can test it wants to do a pull request I will accept it.

**Comment by Zagg3r** [comment]
User neurorulez has added DB15 support to the IremM72 core in the MiSTer-DB9 fork.
Thanks for your great core!
