### ISSUE TITLE
Immortality ??? xmultiply 

### ISSUE THREAD

**Issue by bonna79** [MiSTer-devel/Arcade-IremM72_MiSTer#19]
With the game xmultiply When I play, even if hit by enemies or I collide with obstacles, monsters, I don’t lose lives. As if immortality were active.

**Comment by wickerwaka** [comment]
Sounds like you are playing the "X-Multiply (inv)" mra from the _alternatives directory.

**Comment by bonna79** [comment]
> Sounds like you are playing the "X-Multiply (inv)" mra from the _alternatives directory.

Yes, exactly my mistake, I apologize. I was making the alternative core go.
