### ISSUE TITLE
No analogue audio output for M72 games (works for all other games)

### ISSUE THREAD

**Issue by elrubioVS** [MiSTer-devel/Arcade-IremM72_MiSTer#26]
I’m no longer getting any audio at all from games on the M72 (tested: R-Type 1, 2, Dragonbreed, Air Duel, also Leo on the M92).

The audio works fine for other arcade games.

Audio is connected via the 3.5mm audio jack of the Analogue IO board to the 3.5mm audio input of a soundbar.

Beyond resetting all the settings for each game i’m not sure how else to troubleshoot. Other than rebuilding.

I’ve also used update_all regularly.

Is anyone else seeing this for the games mentioned above after an update_all?

**Comment by elrubioVS** [comment]
I think i've narrowed the issue down to the 3.5mm audio output of the Analogue IO board. But it's still only affects the Irem cores that I know of (i haven't checked all cores).

I've rebuilt the MiSTer project from scratch on the SD card and connected the DE10 to another monitor (which has a built-in speaker) via HDMI. HDMI audio work fine.

When i reconnect the DE10 to my arcade cab (where the monitor does not have a built-in speaker) and use 3.5mm audio output of the Analogue IO board, there is no audio for the Irem core games but there is audio for Marvel VS Capcom for example.

I'll have a read about audio config but is there anything obvious that i'm missing? It all worked fine at one point so there has been a change somewhere to the way audio is managed.

**Comment by elrubioVS** [comment]
**UPDATE:** I've not yet got the Digital IO board but i have noticed more oddities (remember that this is a fresh build of MiSTer).

- All games on the Irem cores & Tecmo cores produce no sound
- Shadow Dancer does not receive an INSERT COIN input even after it allows me to define the INSERT COIN button in the config

Obviously i've not been able to check all games but sound works absolutely fine for most other games as does the INSERT COIN button and functionality.

I'm starting to think that i may have a faulty ram module...

@wickerwaka do you agree with that assessment?

**Comment by wickerwaka** [comment]
I would be surprised if RAM was the issue here. None of the audio functions on the IREM cores uses SDRAM other than sample playback and HDMI audio is functioning fine. I suspect this is an issue with your IO board. The most recent M72 update includes framework changes to support the new 9.2 IO board and it's possible that your IO board is non-standard in some way and isn't being detected correctly.

Have you tried something like SNES, NES or NeoGeo? They have also been updated to this new framework version. JT cores have not yet been updated so if you are still getting audio in those that would be a clue too.

The Shadow Dancer issue is likely something unrelated.

**Comment by elrubioVS** [comment]
> I would be surprised if RAM was the issue here. None of the audio functions on the IREM cores uses SDRAM other than sample playback and HDMI audio is functioning fine. I suspect this is an issue with your IO board. The most recent M72 update includes framework changes to support the new 9.2 IO board and it's possible that your IO board is non-standard in some way and isn't being detected correctly.
> 
> Have you tried something like SNES, NES or NeoGeo? They have also been updated to this new framework version. JT cores have not yet been updated so if you are still getting audio in those that would be a clue too.
> 
> The Shadow Dancer issue is likely something unrelated.

Thanks mate, appreciate you taking the time to read this and respond :)

Thanks for the info, i'll continue with my original plan to replace the IO board then. Incidentally I currently have the Analog IO v5.5 from misterfpga.co.uk

**Comment by elrubioVS** [comment]
Replacing the Analogue IO board with a Digital IO board fixed the issue.

The Shadow Dancer issue was related to a missing jtbeta.zip
